[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production npm run db:migrate:prod && NODE_ENV=production npm start"

[phases.install.caching]
disabled = true
